services:

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: learncrud
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    image: backend:v3
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    image: reactapp:v2
    container_name: reactapp
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
 
